In [1]:
pip install streamlit

Collecting streamlit
  Downloading streamlit-1.60.0-py3-none-any.whl.metadata (10 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.2.2-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting click<9,>=7.0 (from streamlit)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.57-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<3,>=1.23 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit) (2.4.6)
Requirement already satisfied: packaging>=20 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit) (3.0.5)
Requirement already satisfied: pillow<13,>=7.1.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit) (12.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting protobuf<8,>=3.20 (from streamlit)
  Downloading protobuf-7.35.1-cp310-abi3-macosx_10_9_universal2.whl.metadata (595 bytes)
Collecting pyarrow<25,>=7.0 (from streamlit)
  Downloading pyarrow-24.0.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (3.0 kB)
Collecting requests<3,>=2.27 (from streamlit)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit) (4.16.0)
Collecting starlette<2,>=0.40.0 (from streamlit)
  Downloading starlette-1.3.1-py3-none-any.whl.metadata (6.4 kB)
Collecting uvicorn<1,>=0.30.0 (from streamlit)
  Downloading uvicorn-0.52.0-py3-none-any.whl.metadata (6.6 kB)
Collecting httptools<1,>=0.6.3 (from streamlit)
  Downloading httptools-0.8.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (3.5 kB)
Collecting anyio<5,>=4.0.0 (from streamlit)
  Downloading anyio-4.14.2-py3-none-any.whl.metadata (4.6 kB)
Collecting python-multipart<1,>=0.0.10 (from streamlit)
  Downloading python_multipart-0.0.32-py3-none-any.whl.metadata (2.1 kB)
Collecting websockets<17,>=12.0.0 (from streamlit)
  Downloading websockets-16.1.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.8 kB)
Collecting itsdangerous<3,>=2.1.2 (from streamlit)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting jinja2 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: narwhals>=2.4.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.24.0)
Collecting idna>=2.8 (from anyio<5,>=4.0.0->streamlit)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.27->streamlit)
  Downloading charset_normalizer-3.4.9-cp311-cp311-macosx_10_9_universal2.whl.metadata (41 kB)
Collecting urllib3<3,>=1.26 (from requests<3,>=2.27->streamlit)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests<3,>=2.27->streamlit)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting h11>=0.8 (from uvicorn<1,>=0.30.0->streamlit)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting MarkupSafe>=2.0 (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading markupsafe-3.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading rpds_py-2026.6.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (4.1 kB)
Requirement already satisfied: six>=1.5 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.60.0-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 3.2 MB/s  0:00:03 eta 0:00:01
Downloading altair-6.2.2-py3-none-any.whl (797 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 797.6/797.6 kB 3.1 MB/s  0:00:00 eta 0:00:01
Downloading anyio-4.14.2-py3-none-any.whl (125 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading gitpython-3.1.57-py3-none-any.whl (217 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading httptools-0.8.0-cp311-cp311-macosx_11_0_arm64.whl (113 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading protobuf-7.35.1-cp310-abi3-macosx_10_9_universal2.whl (433 kB)
Downloading pyarrow-24.0.0-cp311-cp311-macosx_12_0_arm64.whl (35.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.1/35.1 MB 761.9 kB/s  0:00:38m0:00:0100:02
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 614.0 kB/s  0:00:18m0:00:0100:01
Downloading python_multipart-0.0.32-py3-none-any.whl (30 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.4.9-cp311-cp311-macosx_10_9_universal2.whl (317 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Downloading starlette-1.3.1-py3-none-any.whl (73 kB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading uvicorn-0.52.0-py3-none-any.whl (79 kB)
Downloading websockets-16.1.1-cp311-cp311-macosx_11_0_arm64.whl (177 kB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading markupsafe-3.0.3-cp311-cp311-macosx_11_0_arm64.whl (12 kB)
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-2026.6.3-cp311-cp311-macosx_11_0_arm64.whl (345 kB)
Installing collected packages: websockets, urllib3, toml, tenacity, smmap, rpds-py, python-multipart, pyarrow, protobuf, MarkupSafe, itsdangerous, idna, httptools, h11, click, charset_normalizer, certifi, blinker, attrs, uvicorn, requests, referencing, jinja2, gitdb, anyio, starlette, pydeck, jsonschema-specifications, gitpython, jsonschema, altair, streamlit
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32/32 [streamlit]32 [streamlit]]malizer]
Successfully installed MarkupSafe-3.0.3 altair-6.2.2 anyio-4.14.2 attrs-26.1.0 blinker-1.9.0 certifi-2026.7.22 charset_normalizer-3.4.9 click-8.4.2 gitdb-4.0.12 gitpython-3.1.57 h11-0.16.0 httptools-0.8.0 idna-3.18 itsdangerous-2.2.0 jinja2-3.1.6 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 protobuf-7.35.1 pyarrow-24.0.0 pydeck-0.9.3 python-multipart-0.0.32 referencing-0.37.0 requests-2.34.2 rpds-py-2026.6.3 smmap-5.0.3 starlette-1.3.1 streamlit-1.60.0 tenacity-9.1.4 toml-0.10.2 urllib3-2.7.0 uvicorn-0.52.0 websockets-16.1.1

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install streamlit-option-menu

Collecting streamlit-option-menu
  Downloading streamlit_option_menu-0.4.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: streamlit>=1.36 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit-option-menu) (1.60.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (6.2.2)
Requirement already satisfied: blinker<2,>=1.5.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (8.4.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (3.1.57)
Requirement already satisfied: numpy<3,>=1.23 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (2.4.6)
Requirement already satisfied: packaging>=20 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (3.0.5)
Requirement already satisfied: pillow<13,>=7.1.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (12.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (0.9.3)
Requirement already satisfied: protobuf<8,>=3.20 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (7.35.1)
Requirement already satisfied: pyarrow<25,>=7.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (4.16.0)
Requirement already satisfied: starlette<2,>=0.40.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (1.3.1)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (0.52.0)
Requirement already satisfied: httptools<1,>=0.6.3 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (16.1.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.0)
Requirement already satisfied: jinja2 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2.24.0)
Requirement already satisfied: idna>=2.8 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from anyio<5,>=4.0.0->streamlit>=1.36->streamlit-option-menu) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (5.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from uvicorn<1,>=0.30.0->streamlit>=1.36->streamlit-option-menu) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2026.6.3)
Requirement already satisfied: six>=1.5 in /Users/gyanvi/PycharmProjects/Health-Condition-Prediction/.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (1.17.0)
Downloading streamlit_option_menu-0.4.0-py3-none-any.whl (829 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.3/829.3 kB 2.2 MB/s  0:00:00 eta 0:00:01
Installing collected packages: streamlit-option-menu
Successfully installed streamlit-option-menu-0.4.0

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

# Model Deployment

## Objective

In this notebook, we will validate the complete deployment pipeline.

The trained model, preprocessing pipeline, and label encoder will be loaded from the saved artifacts.

We will:

- Load deployment artifacts
- Load processed test data
- Perform single prediction
- Compare prediction with actual label
- Predict class probabilities
- Perform batch predictions
- Validate the deployment pipeline before building the Streamlit application

At the end of this notebook, we will have a production-ready prediction workflow.

In [12]:
import warnings
warnings.filterwarnings("ignore")

import joblib
import pandas as pd

from pathlib import Path
import sys

In [13]:
project_root = Path.cwd().parent

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

In [14]:
from src.data.dataset_manager import DatasetManager

In [15]:
model = joblib.load(
    "../artifacts/best_model.pkl"
)

preprocessor = joblib.load(
    "../artifacts/preprocessor.pkl"
)

label_encoder = joblib.load(
    "../artifacts/label_encoder.pkl"
)

print("✅ Artifacts Loaded Successfully")

✅ Artifacts Loaded Successfully

In [16]:
dataset_manager = DatasetManager()

X_train_processed, X_test_processed, y_train, y_test = (
    dataset_manager.load_processed_data()
)

print(X_test_processed.shape)

✅ Processed datasets loaded successfully.
(138018, 25)

In [17]:
sample = X_test_processed.head(1)

display(sample)

,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type_balanced,diet_type_non-veg,diet_type_veg,...,sleep_quality_poor,physical_activity_level_active,physical_activity_level_moderate,physical_activity_level_sedentary,smoking_alcohol_no,smoking_alcohol_occasional,smoking_alcohol_yes,gender_female,gender_male,gender_other
0,-0.150712,-0.885602,1.7043,0.708761,1.243157,0.077354,-0.273629,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [18]:
actual_label = y_test.iloc[0]

print("Actual Label :", actual_label)

Actual Label : at-risk

In [19]:
prediction = model.predict(sample)

predicted_label = label_encoder.inverse_transform(
    prediction
)

print("Predicted Label :", predicted_label[0])

Predicted Label : at-risk

In [20]:
probability = model.predict_proba(sample)

probability_df = pd.DataFrame(

    probability,

    columns=label_encoder.classes_

)

display(probability_df)

    at-risk       fit  unhealthy
0  0.998604  0.000017    0.00138

In [21]:
probability = model.predict_proba(sample)

probability_df = pd.DataFrame(
    probability,
    columns=label_encoder.classes_
)

display(probability_df)

predicted_class = probability_df.idxmax(axis=1).iloc[0]
confidence = probability_df.max(axis=1).iloc[0] * 100

print(f"Predicted Class : {predicted_class}")
print(f"Confidence      : {confidence:.2f}%")

    at-risk       fit  unhealthy
0  0.998604  0.000017    0.00138

Predicted Class : at-risk
Confidence      : 99.86%

In [22]:
actual = y_test.iloc[0]

comparison = pd.DataFrame({
    "Actual": [actual],
    "Predicted": [predicted_class],
    "Confidence (%)": [round(confidence, 2)]
})

display(comparison)

    Actual Predicted  Confidence (%)
0  at-risk   at-risk           99.86

In [23]:
batch = X_test_processed.head(10)

predictions = model.predict(batch)

decoded_predictions = label_encoder.inverse_transform(predictions)

probabilities = model.predict_proba(batch)

confidence_scores = probabilities.max(axis=1) * 100

results = pd.DataFrame({
    "Actual": y_test.head(10).values,
    "Predicted": decoded_predictions,
    "Confidence (%)": confidence_scores.round(2)
})

display(results)

    Actual Predicted  Confidence (%)
0  at-risk   at-risk           99.86
1  at-risk   at-risk           98.30
2  at-risk   at-risk           99.40
3  at-risk   at-risk           98.08
4  at-risk   at-risk           99.53
5  at-risk   at-risk           99.09
6  at-risk   at-risk           99.61
7  at-risk   at-risk           98.62
8  at-risk   at-risk           99.36
9  at-risk   at-risk           99.08

In [24]:
from sklearn.metrics import accuracy_score

full_predictions = model.predict(X_test_processed)

deployment_accuracy = accuracy_score(
    label_encoder.transform(y_test),
    full_predictions
)

print(f"Deployment Accuracy : {deployment_accuracy:.4f}")

Deployment Accuracy : 0.9657

In [26]:
from src.pipeline.prediction_pipeline import PredictionPipeline

pipeline = PredictionPipeline()

In [29]:
import pandas as pd

sample = pd.DataFrame({

    "sleep_duration":[7.5],

    "heart_rate":[70],

    "bmi":[23],

    "calorie_expenditure":[2200],

    "step_count":[9000],

    "exercise_duration":[45],

    "water_intake":[2.5],

    "diet_type":["balanced"],

    "stress_level":["low"],

    "sleep_quality":["good"],

    "physical_activity_level":["active"],

    "smoking_alcohol":["no"],

    "gender":["male"]

})

In [30]:
result = pipeline.get_prediction(sample)

print(result)

{'prediction': 'fit', 'probability': array([7.72807989e-03, 9.91482195e-01, 7.89725521e-04]), 'confidence': np.float64(0.991482194585794)}